import random
from typing import List
from customer import ConsumeristCustomer, InAHurryCustomer, RegularCustomer
from environment import Product, ShopEnvironment
import re
from customer_actions import ACTIONS

CUSTOMER_TYPES = [RegularCustomer, RegularCustomer, RegularCustomer]

def run_shop(env, num_cashiers, shop_size, products, shelves_distribution):
    shop = ShopEnvironment(env, shop_size, products, shelves_distribution, num_cashiers)
    
    for id in range(3):
        customer = generate_customer(id, env, shop)
        env.process(go_shopping(env, customer, shop))
        
    while True:
        yield env.timeout(0.20)  # Wait a bit before generating a new customer
        
        id+=1
        customer = generate_customer(id, env, shop)
        env.process(go_shopping(env, customer, shop))

def go_shopping(env, customer, shop):
    
    planning = customer.get_plan()
    
    for plan in planning:
        tokens = tokenize(plan)
        if tokens[0] == 'Buy':
            with shop.cashier.request() as request:
                yield request
                yield env.process(ACTIONS[tokens[0]](shop, customer, tokens[1:]).execute())
                profits_in_time.append(shop.profit)
                print(str(profits_in_time[-1]) + ' generated by ' + str(customer))
        else : yield env.process(ACTIONS[tokens[0]](shop, customer, tokens[1:]).execute())
        
    
def generate_customer(id, env, shop):
    shopping_list = fill_shopping_list(shop)
    arrival_time = env.now
    client_type = random.choice(CUSTOMER_TYPES)
    client = client_type(id, arrival_time, shopping_list, shop)
    return client

def fill_shopping_list(shop):
    products : List[Product] = list(shop.products.values())
    shopping_list = []
    len_shopping_list = random.randint(1, len(products))
    possible_indexes = [i for i in range(len(products))]

    for i in range(len_shopping_list):
        index_value = random.choice(possible_indexes)
        possible_indexes.remove(index_value)
        shopping_list.append(products[index_value])
    
    return shopping_list

def tokenize(plan : str):
    return re.findall(r"[\w']+", plan)
